import { Usuario } from '../interfaces/usuario.interface';

export const USUARIOS_MOCK: Record<string, Usuario> = {
  'pablo.ricardo': {
    id: 1,
    nome: 'Pablo Ricardo',
    login: 'pablo.ricardo',
    matricula: 'pablo.ricardo',
    perfil: 'ADMIN_DTEC',
    email: 'pablo.ricardo@localhost',
    diretoriaSigla: 'DTEC',
  },
  'diretoria': {
    id: 2,
    nome: 'Usuário Diretoria',
    login: 'diretoria',
    matricula: 'diretoria',
    perfil: 'DIRETORIA',
    email: 'diretoria@localhost',
    diretoriaId: 10,
    diretoriaSigla: 'DTEC',
  },
  'comandante': {
    id: 3,
    nome: 'Comandante BPTUR',
    login: 'comandante',
    matricula: 'comandante',
    perfil: 'COMANDANTE',
    email: 'comandante@localhost',
    diretoriaId: 10,
    diretoriaSigla: 'DTEC',
    batalhaoId: 20,
    batalhaoSigla: 'BPTUR',
    secaoId: 101,
    secaoSigla: 'BPTUR',
  },
  'usuariobatalhao': {
    id: 4,
    nome: 'Usuário BPTUR',
    login: 'usuariobatalhao',
    matricula: 'usuariobatalhao',
    perfil: 'USUARIO_BATALHAO',
    email: 'usuariobatalhao@localhost',
    diretoriaId: 10,
    diretoriaSigla: 'DTEC',
    batalhaoId: 20,
    batalhaoSigla: 'BPTUR',
    secaoId: 101,
    secaoSigla: 'BPTUR',
  },
};
