services:
  db:
    image: postgres:15
    container_name: sigmat-postgres
    environment:
      POSTGRES_USER: sigmat_user
      POSTGRES_PASSWORD: sigmat_password
      POSTGRES_DB: sigmat_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
