export const ROTAS = {
  LOGIN: '/login',
  QRCODE: '/qrcode',
  VISAO_GERAL: '/visao-geral',
  INICIO: '/visao-geral/inicio',
  EQUIPAMENTOS: '/visao-geral/equipamentos',
  USUARIOS: '/visao-geral/usuarios',
  CAUTELAS: '/visao-geral/cautelas',
  APROVACOES: '/visao-geral/aprovacoes',
  RELATORIOS: '/visao-geral/relatorios',
  SECOES: '/visao-geral/tabelas-basicas/secoes',
  CONFIGURACOES: '/visao-geral/configuracoes',
  TRANSFERENCIAS: '/visao-geral/transferencias',
  MANUTENCAO: '/visao-geral/manutencao',
  AUDITORIA: '/visao-geral/auditoria',
  TABELAS_TIPOS: '/visao-geral/tabelas-basicas/tipos',
  TABELAS_MARCAS: '/visao-geral/tabelas-basicas/marcas',
  TABELAS_MODELOS: '/visao-geral/tabelas-basicas/modelos',
  TABELAS_STATUS: '/visao-geral/tabelas-basicas/status',
  TABELAS_DISPONIBILIDADES: '/visao-geral/tabelas-basicas/disponibilidades',
} as const;

export const ROTAS_RELATIVAS = {
  INICIO: 'inicio',
  EQUIPAMENTOS: 'equipamentos',
  USUARIOS: 'usuarios',
  CAUTELAS: 'cautelas',
  APROVACOES: 'aprovacoes',
  RELATORIOS: 'relatorios',
  SECOES: 'tabelas-basicas/secoes',
  CONFIGURACOES: 'configuracoes',
  TRANSFERENCIAS: 'transferencias',
  MANUTENCAO: 'manutencao',
  AUDITORIA: 'auditoria',
  TABELAS_TIPOS: 'tabelas-basicas/tipos',
  TABELAS_MARCAS: 'tabelas-basicas/marcas',
  TABELAS_MODELOS: 'tabelas-basicas/modelos',
  TABELAS_STATUS: 'tabelas-basicas/status',
  TABELAS_DISPONIBILIDADES: 'tabelas-basicas/disponibilidades',
} as const;
